CREATE TABLE sibi_users_American (
  nmber Integer Null,
  Gender VARCHAR(6) NULL,
  NameSet VARCHAR (8) NULL,
  Title VARCHAR(4) NULL,
  GivenName VARCHAR(44) NULL,
  MiddleInitial VARCHAR(1) NULL,
  Surname VARCHAR(44) NULL,
  StreetAddress VARCHAR(64) NULL,
  City VARCHAR(44) NULL,
  State CHAR(2),
  StateFull VARCHAR(14) NULL,
  ZipCode CHAR(5) NULL,
  Country VARCHAR(2) NULL,
  CountryFull VARCHAR (13),
  EmailAddress VARCHAR(44) NULL,
  Username VARCHAR(44) NULL,
  Password VARCHAR(44) NULL,
  BrowserUserAgent VARCHAR(188) NULL,
  TelephoneNumber CHAR(12) NULL,
  TelephoneCountryCode CHAR (1) NULL,
  MothersMaiden VARCHAR (44)NULL,
  Birthday CHAR (10),
  Age CHAR (2),
  CCType VARCHAR (10) NULL,
  CCNumber CHAR (16) NULL,
  CVV2 CHAR (3) NULL,
  CCExpires CHAR (8)NULL,
  NationalID CHAR(11)NULL,
  UPS CHAR (28)NULL,
  WesternUnion CHAR (14) NULL,
  MoneyGram CHAR (14)NULL,
  Color CHAR (7) NULL,
  Occupation VARCHAR (111)NULL,
  Company VARCHAR (44)NULL,
  Vehicle VARCHAR (44)NULL,
  Domain VARCHAR(44)NULL,
  GUID CHAR (44)NULL,
  LATITUDE double precision, 
  LONGITUDE double precision

);